theme: minima
name: ozsurvival
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
show_excerpts: true
minima:
  social_links:
    twitter: jekyllrb
    facebook: jekyll
    instagram: ozsurvival
    youtube: jekyll
    youtube_channel: 
    youtube_channel_name: CloudCannon
